import Head from 'next/head';
import Link from 'next/Link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <p>
          Next js follows file based routing. If you want show component when
          you render http://localhost:3000/ You should put that under
          pages/index.js.
        </p>
        <Link href='/posts' passHref>
          <h2>User Posts</h2>
        </Link>
      </main>
    </>
  );
}
