schema: http://localhost:3000/api/graphql
documents: ./queries/**/*.graphql
generates:
  ./types/generatedTypes.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
