import React from 'react';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from 'yup';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const schema = yup.object().shape({
  firstName: yup.string().required('First Name required'),
  lastName: yup.string().required('Last Name required'),
  email: yup.string().email().required('Email required'),
  age: yup.number().positive().required('Age must be a number'),
  password: yup.string().min(4).max(15).required('Password required'),
  confirmPassword: yup.string().oneOf([yup.ref('password'), null]),
});

export default function Home() {
  const {
    register,
    formState: { errors },
    handleSubmit,
  } = useForm({
    resolver: yupResolver(schema),
  });

  const submitForm = (data) => {
    console.log(data);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 style={{ textAlign: 'center' }}>React Forms</h1>
      <div style={{ textAlign: 'center', paddingBottom: '20px' }}>Sign Up</div>
      <div>
        <div
          style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          <form onSubmit={handleSubmit(submitForm)}>
            <input
              type='text'
              name='firstName'
              placeholder='First Name...'
              {...register('firstName')}
            />
            <p> {errors.firstName?.message} </p>
            <input
              type='text'
              name='lastName'
              placeholder='Last Name...'
              ref={register}
              {...register('lastName')}
            />
            <p> {errors.lastName?.message} </p>
            <input
              type='text'
              name='email'
              placeholder='Email...'
              {...register('email')}
            />
            <p> {errors.email?.message} </p>
            <input
              type='text'
              name='age'
              placeholder='Age...'
              {...register('age')}
            />
            <p> {errors.age?.message} </p>
            <input
              type='password'
              name='password'
              placeholder='Password...'
              {...register('password')}
            />
            <p> {errors.password?.message} </p>
            <input
              type='password'
              name='confirmPassword'
              placeholder='Confirm Password...'
              {...register('confirmPassword')}
            />
            <p> {errors.confirmPassword && 'Passwords Should Match!'} </p>
            <div style={{ textAlign: 'center' }}>
              <input type='submit' id='submit' />
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
