export const formData = [
  {
    id: 1,
    name: 'username',
    type: 'text',
    label: 'Username',
    placeholder: 'Username',
    errorMessage:
      "Username should be 3-16 characters and shouldn't include any special character!",
    pattern: '^[A-Za-z0-9]{3,16}$',
    required: true,
  },
  {
    id: 2,
    name: 'email',
    type: 'email',
    label: 'Email',
    placeholder: 'Email',
    required: true,
    errorMessage: 'It should be a valid email address!',
  },
  {
    id: 3,
    name: 'birthday',
    type: 'date',
    label: 'Birthday',
    placeholder: 'Birthday',
    required: true,
  },
  {
    id: 4,
    name: 'password',
    type: 'password',
    label: 'Password',
    placeholder: 'Password',
    required: true,
    errorMessage:
      'Password should be 8-20 characters and include at least 1 letter, 1 number and 1 special character!',
    pattern: `^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{8,20}$`,
  },
  {
    id: 5,
    name: 'confirmPassword',
    type: 'password',
    label: 'Confirm Password',
    placeholder: '****',
    required: true,
    errorMessage: "Passwords don't match!",
  },
];
